#!/bin/bash

WEBROOT=/home/skroes/git/website/demo.hairstudiopinella.nl/public/
SUBDIR=download
OUTPUT="/home/skroes/git/website/demo.hairstudiopinella.nl/public/download/index.html"

i=0
echo "1<UL>" > $OUTPUT
for filepath in `find "${WEBROOT}/${SUBDIR}" -maxdepth 1 -mindepth 1 -type d| sort`; do
  path=`basename "$filepath"`
  echo "  <LI>$path</LI>" >> $OUTPUT
  echo "  <UL>" >> $OUTPUT
  for i in `find "$filepath" -maxdepth 1 -mindepth 1 -type f| sort`; do
    file=`basename "$i"`
    echo "    <LI><a href=\"/${SUBDIR}/$path/$file\">$file</a></LI>" >> $OUTPUT
  done
  echo "  </UL>" >> $OUTPUT
done
echo "</UL>" >> $OUTPUT
